#!/usr/bin/env bash
#
# i3 shutdown menu via rofi.
#
# Menu entries:
#   Shutdown -> systemctl poweroff
#   Reboot   -> systemctl reboot
#   Lock     -> betterlockscreen -l
#   Logout   -> i3-msg exit
#   Cancel   -> do nothing

set -o nounset

# Colors: FG (foreground), BG (background), HL (highlighted)
FG_COLOR="${FG_COLOR:-#bbbbbb}"
BG_COLOR="${BG_COLOR:-#111111}"
HLFG_COLOR="${HLFG_COLOR:-#111111}"
HLBG_COLOR="${HLBG_COLOR:-#bbbbbb}"
BORDER_COLOR="${BORDER_COLOR:-#222222}"

# Rofi options
ROFI_TEXT="${ROFI_TEXT:-}"
ROFI_OPTIONS=(${ROFI_OPTIONS:--theme-str 'window {width: 180px; height:185px;} listview {scrollbar: false;}' -location 0})
ROFI_THEME="$HOME/.config/rofi/config-dmenu.rasi"

# Ask for user's confirmation
enable_confirmation="${ENABLE_CONFIRMATIONS:-false}"

usage="$(basename "$0") [-h] [-c] -- display a menu for shutdown, reboot, lock etc.

where:
    -h  show this help text
    -c  ask for user confirmation

Dependencies: systemd, i3, rofi."

# Parse CLI arguments
while getopts "hc" option; do
  case "${option}" in
    h) echo "${usage}"
       exit 0
       ;;
    c) enable_confirmation=true
       ;;
    *) exit 1
       ;;
  esac
done

# systemctl required
if ! command -v systemctl >/dev/null 2>&1; then
  exit 1
fi

# rofi required
if ! command -v rofi >/dev/null 2>&1; then
  exit 1
fi

# Menu entries that may trigger a confirmation message
menu_confirm="Shutdown Reboot Logout"

# Menu defined as an associative array
typeset -A menu
menu=(
  [Shutdown]="systemctl poweroff"
  [Reboot]="systemctl reboot"
  [Lock]="betterlockscreen -l"
  [Logout]="i3-msg exit"
  [Cancel]=""
)
menu_nrows=${#menu[@]}

rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" \
    -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")
rofi_cmd=(rofi -dmenu -config "$ROFI_THEME" -i -lines "${menu_nrows}" -p "${ROFI_TEXT}" \
    "${rofi_colors[@]}" "${ROFI_OPTIONS[@]}")

ask_confirmation() {
  confirmed=$(printf 'Yes\nNo' | rofi -dmenu -i -lines 2 -p "${selection}?" \
    "${rofi_colors[@]}" "${ROFI_OPTIONS[@]}")
  if [[ "${confirmed}" == "Yes" ]]; then
    i3-msg -q "exec ${menu[${selection}]}"
  fi
}

selection="$(printf '%s\n' "${!menu[@]}" | sort | "${rofi_cmd[@]}")"

if [[ -n "${selection}" ]]; then
  if [[ "${enable_confirmation}" = true && \
        ${menu_confirm} =~ (^|[[:space:]])"${selection}"($|[[:space:]]) ]]; then
    ask_confirmation
  else
    i3-msg -q "exec ${menu[${selection}]}"
  fi
fi